CREATE USER sc_product;
CREATE USER sc_order;
CREATE USER sc_customer;

CREATE SCHEMA IF NOT EXISTS AUTHORIZATION sc_product;
CREATE SCHEMA IF NOT EXISTS AUTHORIZATION sc_order;
CREATE SCHEMA IF NOT EXISTS AUTHORIZATION sc_customer;

ALTER USER sc_product WITH PASSWORD '123456';
ALTER USER sc_order WITH PASSWORD '123456';
ALTER USER sc_customer WITH PASSWORD '123456';
